# Site settings
title: ~dsalaj/com/
email: salaj@gmx.at
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Darjan Salaj, a student of Graz University of Technology
  (TU Graz) and an employee of Institut für Informationssysteme und Computer
  Medien (IICM).
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://dsalaj.com/" # the base hostname & protocol for your site
github_username:  dsalaj

# Build settings
markdown: kramdown
highlighter: rouge

# Comment section
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSfZygIyduVO5vBTik9OlgVkRkln01z312kCIw1r0zNtk1p9rQ
comment-read: https://docs.google.com/spreadsheets/d/1907jNfDtflLrSLoxw2kRBM5Ccs_wXhPa6fZEBC1rIes
comment-post-fields: [ entry.558637440, entry.1076142172, entry.2116515924 ]
